"on":
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch: {}
name: Update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/github-app-token-action@v1
        id: app-token
        with:
          app_id: ${{ vars.ALL_CONTRIBUTORS_IMPORT_APP_ID }}
          private_key: ${{ secrets.ALL_CONTRIBUTORS_IMPORT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - run: npm ci
      - run: node bin/cli.js
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Create or update pull request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          title: 🤖📯 Endorsements Update
          body: >
            I found new endorsements and thought I'd let you know about it 👋🤖
          branch: update
          author: '"all-contributors-import[bot]" <138532524+all-contributors-import[bot]@users.noreply.github.com>'
          commit-message: "data: update"
